pr: none
trigger: none
schedules: PLACEHOLDER
resources:
  repositories:
  - repository: BCDevOpsFlows
    type: github
    name: PLACEHOLDER
    endpoint: PLACEHOLDER
pool:
  name: PLACEHOLDER
variables:
- group: PLACEHOLDER
jobs:
- job: IncrementMinorVersion
  timeoutInMinutes: 300
  variables:
    AL_PIPELINENAME: IncrementMinorVersion
  steps:
  - checkout: self
    path: App
    persistCredentials: true
    clean: true
  - checkout: BCDevOpsFlows
    path: BCDevOpsFlows
  - task: PowerShell@2
    displayName: Initialize
    inputs:
      pwsh: true
      filePath: ..\BCDevOpsFlows\WorkflowInitialize\WorkflowInitialize.ps1
  - task: PowerShell@2
    displayName: Read Settings
    inputs:
      pwsh: true
      filePath: ..\BCDevOpsFlows\ReadSettings\ReadSettings.ps1
  - task: PowerShell@2
    displayName: Increment Minor Version
    inputs:
      pwsh: true
      filePath: ..\BCDevOpsFlows\IncrementVersion\IncrementVersion.ps1
      arguments: -versionNumber "+0.1"
      failOnStderr: true
      warningPreference: continue
      showWarnings: true
  - task: PowerShell@2
    displayName: Push Changes Back to Repo (if any)
    inputs:
      pwsh: true
      filePath: ..\BCDevOpsFlows\PushBackToRepo\PushBackToRepo.ps1
      failOnStderr: true
      warningPreference: continue
      showWarnings: true
  - task: PowerShell@2
    displayName: Cleanup
    condition: always()
    inputs:
      pwsh: true
      filePath: ..\BCDevOpsFlows\PipelineCleanup\PipelineCleanup.ps1
      failOnStderr: false


