pr: none
trigger: 
- cron: '0 2 1 1,2,3,5,6,7,8,9,11,12 *'
  displayName: First of every month except April and October
  branches:
    include:
    - main
    - master
    - preview
    - test

resources:
  repositories:
  - repository: BCDevOpsFlows
    type: github
    name: # Specify the link to your BCDevOpsFlows fork (format YourGitHubUsername/ForkName)
    endpoint: # Specify the name of the service connection with access to your fork

pool:
  name: # Specify the name of the pool of your self-hosted agents

variables:
- group: BCDevOpsFlows

jobs:
- job: Increment_Minor_Version
  timeoutInMinutes: 300
  variables:
    AL_PIPELINENAME: 'IncrementMinorVersion'

  steps:
  - checkout: self
    path: App
    persistCredentials: true
    clean: true
  - checkout: BCDevOpsFlows
    path: BCDevOpsFlows

  - task: PowerShell@2
    displayName: 'Initialize'
    inputs:
      pwsh: true
      filePath: '..\BCDevOpsFlows\WorkflowInitialize\WorkflowInitialize.ps1'

  - task: PowerShell@2
    displayName: 'Read Settings'
    inputs:
      pwsh: true
      filePath: '..\BCDevOpsFlows\ReadSettings\ReadSettings.ps1'

  - task: PowerShell@2
    displayName: 'Increment Minor Version'
    inputs:
      pwsh: true
      filePath: '..\BCDevOpsFlows\IncrementVersion\IncrementVersion.ps1'
      arguments: '-versionNumber "+0.1"'
      failOnStderr: true
      warningPreference: 'continue'
      showWarnings: true

  - task: PowerShell@2
    displayName: 'Push Changes Back to Repo (if any)'
    inputs:
      pwsh: true
      filePath: '..\BCDevOpsFlows\PushBackToRepo\PushBackToRepo.ps1'
      failOnStderr: true
      warningPreference: 'continue'
      showWarnings: true

  - task: PowerShell@2
    displayName: 'Cleanup'
    condition: always()
    inputs:
      pwsh: true
      filePath: '..\BCDevOpsFlows\PipelineCleanup\PipelineCleanup.ps1'
      failOnStderr: false
