pr: none
trigger: none
resources:
  repositories:
  - repository: BCDevOpsFlows
    type: github
    name: ------ REPLACE -------
    endpoint: ------ REPLACE -------
    ref: ------ REPLACE -------
pool:
  vmImage: windows-latest
jobs:
- job: SetupPipelines
  timeoutInMinutes: 300
  variables:
    AL_DEBUG: "true"
    AL_PIPELINENAME: SetupPipelines
  steps:
  - checkout: self
    path: App
    persistCredentials: true
    clean: true
  - checkout: BCDevOpsFlows
    path: BCDevOpsFlows
  - task: PowerShell@2
    displayName: Initialize
    inputs:
      pwsh: true
      filePath: ..\BCDevOpsFlows\WorkflowInitialize\WorkflowInitialize.ps1
  - task: PowerShell@2
    displayName: Setup Pipelines
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
    inputs:
      pwsh: true
      filePath: ..\BCDevOpsFlows\SetupPipelines\SetupPipelines.ps1


